#Funding config file

funding_default:
  scrapers_with_defaults:
    - "funding_afg"
    - "funding_bfa"
    - "funding_caf"
    - "funding_cmr"
    - "funding_cod"
    - "funding_col"
    - "funding_eth"
    - "funding_gtm"
    - "funding_hnd"
    - "funding_hti"
    - "funding_mli"
    - "funding_mmr"
    - "funding_moz"
    - "funding_ner"
    - "funding_nga"
    - "funding_pse"
    - "funding_sdn"
    - "funding_slv"
    - "funding_som"
    - "funding_ssd"
    - "funding_syr"
    - "funding_tcd"
    - "funding_ukr"
    - "funding_ven"
    - "funding_yem"
  input:
    - "#activity+appeal+id+external"
    - "#activity+appeal+name"
    - "#activity+appeal+type+name"
    - "#value+funding+required+usd"
    - "#value+funding+total+usd"
    - "#value+funding+pct"
    - "#date+start"
    - "#date+end"
  list:
    - "#activity+appeal+id+external"
    - "#activity+appeal+name"
    - "#activity+appeal+type+name"
    - "#value+funding+required+usd"
    - "#value+funding+total+usd"
    - "#value+funding+pct"
    - "#date+start"
    - "#date+end"
  output:
    - "#activity+appeal+id+external"
    - "#activity+appeal+name"
    - "#activity+appeal+type+name"
    - "#value+funding+required+usd"
    - "#value+funding+total+usd"
    - "#value+funding+pct"
    - "#date+start"
    - "#date+end"
  output_hxl:
    - "#activity+appeal+id+external"
    - "#activity+appeal+name"
    - "#activity+appeal+type+name"
    - "#value+funding+required+usd"
    - "#value+funding+total+usd"
    - "#value+funding+pct"
    - "#date+start"
    - "#date+end"

funding_national:
  funding_afg:
    dataset: "fts-requirements-and-funding-data-for-afghanistan"
    resource: "fts_requirements_funding_afg.csv"
    admin_single: "AFG"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_bfa:
    dataset: "fts-requirements-and-funding-data-for-burkina-faso"
    resource: "fts_requirements_funding_bfa.csv"
    admin_single: "BFA"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_caf:
    dataset: "fts-requirements-and-funding-data-for-central-african-republic"
    resource: "fts_requirements_funding_caf.csv"
    admin_single: "CAF"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_cmr:
    dataset: "fts-requirements-and-funding-data-for-cameroon"
    resource: "fts_requirements_funding_cmr.csv"
    admin_single: "CMR"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_cod:
    dataset: "fts-requirements-and-funding-data-for-congo-the-democratic-republic-of-the"
    resource: "fts_requirements_funding_cod.csv"
    admin_single: "COD"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_col:
    dataset: "fts-requirements-and-funding-data-for-colombia"
    resource: "fts_requirements_funding_col.csv"
    admin_single: "COL"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_eth:
    dataset: "fts-requirements-and-funding-data-for-ethiopia"
    resource: "fts_requirements_funding_eth.csv"
    admin_single: "ETH"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_gtm:
    dataset: "fts-requirements-and-funding-data-for-guatemala"
    resource: "fts_requirements_funding_gtm.csv"
    admin_single: "GTM"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_hnd:
    dataset: "fts-requirements-and-funding-data-for-honduras"
    resource: "fts_requirements_funding_hnd.csv"
    admin_single: "HND"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_hti:
    dataset: "fts-requirements-and-funding-data-for-haiti"
    resource: "fts_requirements_funding_hti.csv"
    admin_single: "HTI"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_mli:
    dataset: "fts-requirements-and-funding-data-for-mali"
    resource: "fts_requirements_funding_mli.csv"
    admin_single: "MLI"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_mmr:
    dataset: "fts-requirements-and-funding-data-for-myanmar"
    resource: "fts_requirements_funding_mmr.csv"
    admin_single: "MMR"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_moz:
    dataset: "fts-requirements-and-funding-data-for-mozambique"
    resource: "fts_requirements_funding_moz.csv"
    admin_single: "MOZ"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_ner:
    dataset: "fts-requirements-and-funding-data-for-niger"
    resource: "fts_requirements_funding_ner.csv"
    admin_single: "NER"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_nga:
    dataset: "fts-requirements-and-funding-data-for-nigeria"
    resource: "fts_requirements_funding_nga.csv"
    admin_single: "NGA"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_pse:
    dataset: "fts-requirements-and-funding-data-for-occupied-palestinian-territory"
    resource: "fts_requirements_funding_pse.csv"
    admin_single: "PSE"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_sdn:
    dataset: "fts-requirements-and-funding-data-for-sudan"
    resource: "fts_requirements_funding_sdn.csv"
    admin_single: "SDN"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_slv:
    dataset: "fts-requirements-and-funding-data-for-el-salvador"
    resource: "fts_requirements_funding_slv.csv"
    admin_single: "SLV"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_som:
    dataset: "fts-requirements-and-funding-data-for-somalia"
    resource: "fts_requirements_funding_som.csv"
    admin_single: "SOM"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_ssd:
    dataset: "fts-requirements-and-funding-data-for-south-sudan"
    resource: "fts_requirements_funding_ssd.csv"
    admin_single: "SSD"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_syr:
    dataset: "fts-requirements-and-funding-data-for-syrian-arab-republic"
    resource: "fts_requirements_funding_syr.csv"
    admin_single: "SYR"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_tcd:
    dataset: "fts-requirements-and-funding-data-for-chad"
    resource: "fts_requirements_funding_tcd.csv"
    admin_single: "TCD"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_ukr:
    dataset: "fts-requirements-and-funding-data-for-ukraine"
    resource: "fts_requirements_funding_ukr.csv"
    admin_single: "UKR"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_ven:
    dataset: "fts-requirements-and-funding-data-for-venezuela-bolivarian-republic-of"
    resource: "fts_requirements_funding_ven.csv"
    admin_single: "VEN"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"

  funding_yem:
    dataset: "fts-requirements-and-funding-data-for-yemen"
    resource: "fts_requirements_funding_yem.csv"
    admin_single: "YEM"
    format: "csv"
    headers: 1
    use_hxl: True
    filter_cols:
      - "#value+funding+required+usd"
    prefilter: "#value+funding+required+usd is not None"
